
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace DataAccessLayer
{

using System;
    using System.Collections.Generic;
    
public partial class Cvs
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Cvs()
    {

        this.JobExperiences = new HashSet<JobExperiences>();

        this.Schools = new HashSet<Schools>();

        this.isTecrubesi = new HashSet<isTecrubesi>();

    }


    public int id { get; set; }

    public string GitHubLink { get; set; }

    public string CoverLetter { get; set; }

    public bool Active { get; set; }

    public Nullable<int> Aday_Id { get; set; }

    public Nullable<int> Candidate_Id { get; set; }



    public virtual Adays Adays { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<JobExperiences> JobExperiences { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Schools> Schools { get; set; }

    public virtual Adays Adays1 { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<isTecrubesi> isTecrubesi { get; set; }

}

}
